<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Surveillance Summary Report</title>
</head>
<body>
<?php
require __DIR__ . '/navigation.php';

$pdfMode = !empty($pdfMode);
$esc = static fn($v) => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$backUrl = function_exists('route') ? route('general.report') : 'general_report.php';
$printParams = array_filter([
    'declaration_id' => $declarationId ?? ($declaration->declaration_id ?? null),
    'employee_id' => $selectedEmployee->employee_id ?? null,
    'company_id' => $selectedCompany->company_id ?? null,
    'surveillance_id' => $surveillanceId ?? null,
], static fn($value) => $value !== null && $value !== '');
$printUrl = function_exists('route') ? route('pdf.usechh4', $printParams) : 'PDF_USECHH4.php';

$resolvedUser = class_exists('\Illuminate\Support\Facades\Auth') ? \Illuminate\Support\Facades\Auth::user() : null;
$footerFirst = trim((string) (($resolvedUser->first_name ?? $resolvedUser->firstName ?? '') ?: ''));
$footerLast = trim((string) (($resolvedUser->last_name ?? $resolvedUser->lastName ?? '') ?: ''));
$footerName = trim($footerFirst . ' ' . $footerLast);
if ($footerName === '') {
    $footerName = trim((string) (($resolvedUser->name ?? $username ?? 'User') ?: 'User'));
}
$generatedFooter = 'Generated by ' . $footerName . ' at ' . date('D, d M Y h:i A');

$db = class_exists('\Illuminate\Support\Facades\DB') ? \Illuminate\Support\Facades\DB::class : null;
$summaryRow = null;
if ($db && !empty($selectedEmployee->employee_id) && !empty($surveillanceId)) {
    $summaryRow = \Illuminate\Support\Facades\DB::table('summary_report')
        ->where('employee_id', (int) $selectedEmployee->employee_id)
        ->where('surveillance_id', (int) $surveillanceId)
        ->first();
}

$companyId = (int) ($selectedCompany->company_id ?? 0);
$employeeId = (int) ($selectedEmployee->employee_id ?? 0);
$employeeCount = 0;
if ($db && $companyId > 0) {
    $employeeCount = (int) \Illuminate\Support\Facades\DB::table('declaration')
        ->where('company_id', $companyId)
        ->distinct('employee_id')
        ->count('employee_id');
}

$yesNoFromValue = static function ($value): string {
    $value = trim((string) ($value ?? ''));
    if ($value === '') {
        return 'N/A';
    }
    return strcasecmp($value, 'Yes') === 0 ? 'Yes' : 'No';
};
$joinList = static function (array $items, string $fallback = 'N/A'): string {
    $items = array_values(array_filter(array_map(static fn($item) => trim((string) ($item ?? '')), $items), static fn($item) => $item !== ''));
    return $items === [] ? $fallback : implode(', ', $items);
};
$num = static function ($value, string $fallback = '0'): string {
    $value = trim((string) ($value ?? ''));
    return $value === '' ? $fallback : $value;
};
$fmtDate = static function ($value, string $fallback = 'N/A'): string {
    $value = trim((string) ($value ?? ''));
    if ($value === '') {
        return $fallback;
    }
    $time = strtotime($value);
    return $time ? date('d/m/Y', $time) : $value;
};

$workplaceName = trim((string) ($selectedCompany->company_name ?? ''));
$registrationNo = trim((string) (($selectedCompany->mykpp_registration_no ?? $selectedCompany->company_registrationNo ?? '')));
$workplaceAddress = trim((string) ($selectedCompany->company_address ?? ''));
$individualChemical = trim((string) ($chemicalInfo->chemicals ?? ''));
$chraDate = $summaryRow->date_CHRA ?? null;
$chraReportNo = trim((string) ($summaryRow->CHRA_reportNo ?? ''));
$chraReport = trim((string) ($summaryRow->CHRA_report ?? ''));
$joinNatural = static function (array $items, string $fallback = 'N/A'): string {
    $items = array_values(array_filter(array_map(static fn($item) => trim((string) ($item ?? '')), $items), static fn($item) => $item !== ''));
    if ($items === []) {
        return $fallback;
    }
    if (count($items) === 1) {
        return $items[0];
    }
    if (count($items) === 2) {
        return $items[0] . ' and ' . $items[1];
    }
    $last = array_pop($items);
    return implode(', ', $items) . ' and ' . $last;
};

$indicationItems = [];
$chraLower = strtolower($chraReport);
if (str_contains($chraLower, 'reported')) { $indicationItems[] = 'Reported health effects'; }
if (str_contains($chraLower, 'skin')) { $indicationItems[] = 'Skin absorption'; }
if (str_contains($chraLower, 'significant') || str_contains($chraLower, 'pel')) { $indicationItems[] = 'Significant personal exposure (>= 50% PEL)'; }
if (str_contains($chraLower, 'other') && !in_array('Others', $indicationItems, true)) { $indicationItems[] = 'Others'; }
$indicationText = $indicationItems !== [] ? $joinNatural($indicationItems) : ($chraReport !== '' ? $chraReport : 'N/A');
$decisionValue = trim((string) ($summaryRow->decision ?? ''));
if ($decisionValue === '') { $decisionValue = 'N/A'; }

$totalWorkers = $summaryRow->no_workers ?? ($selectedCompany->total_workers ?? $employeeCount);
$workUnit = trim((string) ($summaryRow->work_unit ?? ''));
$exposedWorkers = $summaryRow->no_exposed_workers ?? '';
$examinedWorkers = $summaryRow->no_examined ?? ($employeeId > 0 ? 1 : '');

$healthYes = false;
if (!empty($historyOfHealth)) {
    foreach (get_object_vars($historyOfHealth) as $field => $value) {
        if (in_array($field, ['employee_id', 'surveillance_id', 'others_symptoms'], true)) {
            continue;
        }
        if (trim((string) $value) === 'Yes') {
            $healthYes = true;
            break;
        }
    }
}
$healthText = $summaryRow ? $num($summaryRow->no_workers ?? '', '0') : ($healthYes ? 'Yes' : 'No');
$clinicalText = trim((string) ($msFindings->clinical_findings ?? $clinicalFindings->result_clinical_findings ?? ''));
$targetOrganText = $joinList([
    !empty($targetOrgan->blood_count) ? 'Full blood count' : null,
    !empty($targetOrgan->renal_function) ? 'Renal Profile' : null,
    !empty($targetOrgan->liver_function) ? 'Liver Profile' : null,
    !empty($targetOrgan->chest_xray) ? 'Chest X-ray' : null,
    ($targetOrgan->spirometry_FEV1 ?? null) !== null || ($targetOrgan->spirometry_FVC ?? null) !== null || ($targetOrgan->spirometry_FEV_FVC ?? null) !== null ? 'Spirometry' : null,
], 'N/A');
$beiText = $joinList([
    $biologicalMonitoring->baseline_annual ?? null,
    $biologicalMonitoring->baseline_results ?? null,
    $biologicalMonitoring->biological_exposure ?? null,
], 'N/A');
$workRelatedFlags = [
    trim((string) ($msFindings->CF_work_related ?? '')),
    trim((string) ($msFindings->TO_work_related ?? '')),
    trim((string) ($msFindings->BM_work_related ?? '')),
];
$answeredFlags = array_values(array_filter($workRelatedFlags, static fn($value) => $value !== ''));
$workRelatedText = $answeredFlags === []
    ? 'N/A'
    : (in_array('Yes', $answeredFlags, true) ? 'Yes' : (count(array_filter($answeredFlags, static fn($value) => $value === 'No')) === count($answeredFlags) ? 'No' : 'N/A'));
$conclusionText = trim((string) ($msFindings->conclusion_fitness ?? ''));
$mrpCount = $summaryRow->no_MRP ?? ($conclusionText === 'Not Fit' ? 1 : 0);
$laboratory = trim((string) ($summaryRow->laboratory ?? ''));
$recommendationText = trim((string) ($summaryRow->recommendation ?? ''));
$decisionContinue = trim((string) ($summaryRow->decision ?? '')) === 'Continue MS';
$decisionStop = trim((string) ($summaryRow->decision ?? '')) === 'Stop MS';
$decisionJustification = trim((string) ($summaryRow->justification_decision ?? ''));
$dateImplementation = $summaryRow->date_implementation ?? null;
$doctorName = trim((string) ((($doctor->doctor_firstName ?? '') . ' ' . ($doctor->doctor_lastName ?? ''))));
$doctorReg = trim((string) (($doctor->doctor_registrationNo ?? $doctor->OHD_registrationNo ?? '')));
$doctorPractice = trim((string) ($doctor->doctor_practiceAddress ?? ''));
$doctorTel = trim((string) ($doctor->doctor_telephone ?? ''));
$doctorHp = trim((string) ($doctor->doctor_hpNo ?? ''));
$doctorFax = trim((string) ($doctor->doctor_faxNo ?? ''));
$doctorEmail = trim((string) ($doctor->doctor_email ?? ''));
$currentDate = $chemicalInfo->examination_date ?? null;

medis_render_navigation_start([
    'clinicName' => $clinicName ?? 'Medis SHAMS',
    'clinicLogoUrl' => $clinicLogoUrl ?? null,
    'username' => $username ?? 'User',
    'active' => '',
    'pdfMode' => $pdfMode,
]);
?>
<style>
.report-page{width:100%;max-width:none;margin:0;background:#fff;color:#0f172a;font-family:"Poppins","Segoe UI",Tahoma,Geneva,Verdana,sans-serif}.sheet{padding:18px 18px 22px;border:1px solid #e5e7eb;border-radius:20px;background:#fff;box-shadow:0 10px 30px rgba(15,23,42,.04);width:100%}.sheet-top{position:relative;display:block;margin-bottom:8px;text-align:center}.sheet-top .center-title{display:block;width:100%;text-align:center;font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}.sheet-top .right-code{position:absolute;right:0;top:0;display:block;text-align:right;font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}.sheet-title{text-align:center;margin-bottom:12px}.sheet-title .line{font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}.sheet-title .main{font-size:16px;font-weight:700;line-height:1.5;margin-top:8px;color:#0f172a}.toolbar-hide .app-card{padding:0;border:0;background:transparent;box-shadow:none}.toolbar-hide .app-page{padding:18px;background:#f3f6f8}.report-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:16px}.report-btn{display:inline-flex;align-items:center;gap:8px;text-decoration:none;border:1px solid #d1d5db;border-radius:10px;padding:8px 12px;background:#fff;color:#374151;font-size:14px;cursor:pointer}.report-btn.primary{background:#389B5B;border-color:#389B5B;color:#fff}.meta{display:grid;gap:8px;margin:14px 0 16px;font-size:14px}.meta-row{display:flex;align-items:flex-end;gap:8px}.meta-label{min-width:160px;font-weight:600;color:#0f172a}.meta-value{flex:1;color:#334155}.summary-lines{display:grid;gap:6px;margin:14px 0 12px;font-size:14px}.summary-line{display:flex;align-items:flex-start;gap:8px}.summary-label{min-width:340px;font-weight:600;color:#0f172a}.summary-value{flex:1;color:#334155}.table-wrap{overflow:auto;border:1px solid #dfe5ea;border-radius:18px;background:#fff;margin:12px 0}.exam-table{width:100%;border-collapse:collapse;min-width:760px;table-layout:fixed}.exam-table th,.exam-table td{border:1px solid #dfe5ea;padding:10px 12px;vertical-align:top;font-size:13px;line-height:1.4}.exam-table thead th{background:#eef7f0;font-size:.84rem;font-weight:700;color:#1f2937;text-align:center}.exam-table tbody th,.exam-table tbody td.label-cell{background:#f8fbf8;font-weight:600;text-align:left;color:#14321f}.exam-table.clean-report tbody td{background:#fff;color:#334155}.exam-table.clean-report td.center{text-align:center}.foot-note{padding:10px 12px;border:1px solid #dfe5ea;border-top:0;border-radius:0 0 18px 18px;font-size:13px;font-weight:600;color:#0f172a;background:#fff}.section-stack{display:grid;gap:8px;margin-top:14px}.sign-row{display:grid;grid-template-columns:1fr 1fr;gap:32px;margin-top:24px}.sign-field{display:grid;gap:8px}.pdf-footer{margin-top:14px;padding-top:8px;border-top:1px solid #e5e7eb;text-align:right;font-size:11px;color:#64748b}.pdf-mode .sheet{padding:0;border:0;border-radius:0;box-shadow:none}.pdf-mode .app-page{padding:0!important;background:#fff}.pdf-mode .report-page{padding:0;background:#fff}.pdf-mode .report-actions{display:none!important}.pdf-mode .pdf-footer{position:fixed;left:0;right:0;bottom:0;margin:0;padding-top:6px;background:#fff;border-top:1px solid #e5e7eb}@media print{body{background:#fff}.app-topbar,.app-sidebar,.report-actions{display:none!important}.app-shell{display:block}.app-main,.app-page,.app-card{display:block;height:auto;overflow:visible;padding:0!important;border:0!important;background:#fff!important}.sheet{padding:0;border:0;box-shadow:none}.report-page{max-width:none}}@media(max-width:980px){.sign-row{grid-template-columns:1fr}.report-page{overflow:auto;width:100%}.meta-row,.summary-line{display:grid;gap:4px}.meta-label,.summary-label{min-width:0}}
</style>
<div class="report-page toolbar-hide<?php echo $pdfMode ? ' pdf-mode' : ''; ?>">
    <div class="sheet">
        <div class="sheet-top">
            <span class="center-title">Occupational Safety &amp; Health Act 1994 (Act 514)</span>
            <span class="right-code">USECHH 4</span>
        </div>

        <div class="sheet-title">
            <div class="line">Use and Standard of Exposure of Chemicals Hazardous to Health Regulations 2000</div>
            <div class="main">SUMMARY REPORT FOR MEDICAL SURVEILLANCE</div>
        </div>

        <div class="meta">
            <div class="meta-row"><span class="meta-label">Name of Workplace: </span><span class="meta-value"><?php echo $esc($workplaceName !== '' ? $workplaceName : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">MyKKP Registration No.: </span><span class="meta-value"><?php echo $esc($registrationNo !== '' ? $registrationNo : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">Address of Workplace: </span><span class="meta-value"><?php echo $esc($workplaceAddress !== '' ? $workplaceAddress : 'N/A'); ?></span></div>
        </div>
        <div class="summary-lines">
            <div class="summary-line"><span class="summary-label">Total number of workers in the workplace: </span><span class="summary-value"><?php echo $esc($num($totalWorkers, '0')); ?></span></div>
            <div class="summary-line"><span class="summary-label">Name of the work unit where workers are in: </span><span class="summary-value"><?php echo $esc($workUnit !== '' ? $workUnit : 'N/A'); ?></span></div>
            <div class="summary-line"><span class="summary-label">Total number of exposed workers in the work unit: </span><span class="summary-value"><?php echo $esc($num($exposedWorkers, '0')); ?></span></div>
            <div class="summary-line"><span class="summary-label">Total number of workers examined: </span><span class="summary-value"><?php echo $esc($num($examinedWorkers, '0')); ?></span></div>
        </div>

        <div class="meta">
            <div class="meta-row"><span class="meta-label">Individual Chemical: </span><span class="meta-value"><?php echo $esc($individualChemical !== '' ? $individualChemical : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">Date of CHRA conducted:</span><span class="meta-value"><?php echo $esc($fmtDate($chraDate)); ?></span></div>
            <div class="meta-row"><span class="meta-label">CHRA report no.: </span><span class="meta-value"><?php echo $esc($chraReportNo !== '' ? $chraReportNo : 'N/A'); ?></span></div>
        </div>

        <div class="meta-row"><span class="meta-label">Indication for medical surveillance based on CHRA report: </span><span class="meta-value"><?php echo $esc($indicationText); ?></span></div>

        <div class="table-wrap"><table class="exam-table clean-report">
            <thead>
                <tr><th colspan="5">MEDICAL SURVEILLANCE RESULTS</th></tr>
                <tr>
                    <th rowspan="2" style="width:30%;">&nbsp;</th>
                    <th rowspan="2" style="width:14%;">No. of workers with normal findings</th>
                    <th colspan="2" style="width:32%;">No. of workers with abnormal findings</th>
                    <th rowspan="2" style="width:24%;">No. of workers recommended for medical removal protection</th>
                </tr>
                <tr>
                    <th>Occupational</th>
                    <th>Non-occupational</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td class="label-cell">History of health effects due to chemical exposure (*H)</td>
                    <td><?php echo $esc($healthText); ?></td>
                    <td><?php echo $esc($conclusionText === 'Not Fit' ? '1' : '0'); ?></td>
                    <td>Not applicable</td>
                    <td>Not applicable</td>
                </tr>
                <tr>
                    <td class="label-cell">Clinical findings (*I)</td>
                    <td><?php echo $esc($clinicalText !== '' ? $clinicalText : 'N/A'); ?></td>
                    <td><?php echo $esc($conclusionText === 'Not Fit' && $clinicalText !== '' ? '1' : '0'); ?></td>
                    <td><?php echo $esc($conclusionText !== 'Not Fit' && $clinicalText !== '' ? '1' : '0'); ?></td>
                    <td><?php echo $esc($conclusionText === 'Not Fit' ? '1' : '0'); ?></td>
                </tr>
                <tr>
                    <td class="label-cell">Target organ function test(s) (*J). Please specify:</td>
                    <td><?php echo $esc($targetOrganText); ?></td>
                    <td><?php echo $esc($conclusionText === 'Not Fit' && $targetOrganText !== 'N/A' ? '1' : '0'); ?></td>
                    <td><?php echo $esc($conclusionText !== 'Not Fit' && $targetOrganText !== 'N/A' ? '1' : '0'); ?></td>
                    <td><?php echo $esc($conclusionText === 'Not Fit' ? '1' : '0'); ?></td>
                </tr>
                <tr>
                    <td class="label-cell">BEI determinant (*K) (BM/BEM). Please specify determinant:</td>
                    <td><?php echo $esc($beiText); ?></td>
                    <td><?php echo $esc($conclusionText === 'Not Fit' && $beiText !== 'N/A' ? '1' : '0'); ?></td>
                    <td><?php echo $esc($conclusionText !== 'Not Fit' && $beiText !== 'N/A' ? '1' : '0'); ?></td>
                    <td><?php echo $esc($conclusionText === 'Not Fit' ? '1' : '0'); ?></td>
                </tr>
            </tbody>
        </table><div class="foot-note">Continue in separate sheet if required. Please include details of abnormal examination/test results in USECHH 5ii form and Medical Removal Protection in USECHH 5i form.</div></div>

        <div class="section-stack">
            <div class="meta-row"><span class="meta-label">Total no. of employees recommended for MRP: </span><span class="meta-value"><?php echo $esc(trim((string) ($mrpCount ?? '')) !== '' ? (string) $mrpCount : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">Name of Laboratory: </span><span class="meta-value"><?php echo $esc($laboratory !== '' ? $laboratory : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">Recommendation: </span><span class="meta-value"><?php echo $esc($recommendationText !== '' ? $recommendationText : 'N/A'); ?></span></div>
        </div>
        <div class="section-stack">
            <div class="meta-row"><span class="meta-label">Decision: </span><span class="meta-value"><?php echo $esc($decisionValue); ?></span></div>
            <div class="meta-row"><span class="meta-label">Justification of Decision: </span><span class="meta-value"><?php echo $esc($decisionJustification !== '' ? $decisionJustification : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">Date of Implementation: </span><span class="meta-value"><?php echo $esc($fmtDate($dateImplementation)); ?></span></div>
        </div>

        <div class="section-stack">
            <div>I hereby declare that all particulars given in this report are accurate to the best of my knowledge.</div>
        </div>

        <div class="meta" style="margin-top:16px;">
            <div class="meta-row"><span class="meta-label">Name of occupational Health Doctor: </span><span class="meta-value"><?php echo $esc($doctorName !== '' ? $doctorName : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">OHD Registration No: </span><span class="meta-value"><?php echo $esc($doctorReg !== '' ? $doctorReg : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">Name of Practice &amp; Address: </span><span class="meta-value"><?php echo $esc($doctorPractice !== '' ? $doctorPractice : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">Tel No: </span><span class="meta-value"><?php echo $esc($doctorTel !== '' ? $doctorTel : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">HP no: </span><span class="meta-value"><?php echo $esc($doctorHp !== '' ? $doctorHp : 'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">Fax No: </span><span class="meta-value"><?php echo $esc($doctorFax !== '' ? $doctorFax:  'N/A'); ?></span></div>
            <div class="meta-row"><span class="meta-label">Email address:  </span><span class="meta-value"><?php echo $esc($doctorEmail !== '' ? $doctorEmail : 'N/A'); ?></span></div>
        </div>

        <div class="sign-row">
            <div class="sign-field"><span class="meta-label">Date:</span><span class="meta-value"><?php echo $esc($fmtDate($currentDate)); ?></span></div>
            <div class="sign-field"><span class="meta-label">Signature:</span><span class="meta-value"><?php echo $esc('Saved in system'); ?></span></div>
        </div>

        <div class="pdf-footer"><?php echo $esc($generatedFooter); ?></div>
    </div>

    <?php if (!$pdfMode): ?>
    <div class="report-actions">
        <a class="report-btn" href="<?php echo $esc($backUrl); ?>">Back</a>
        <a class="report-btn primary" href="<?php echo $esc($printUrl); ?>" target="_blank" rel="noopener">Print</a>
    </div>
    <?php endif; ?>
</div>
<?php medis_render_navigation_end(); ?>
</body>
</html>









