<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Surveillance Summary Employee Report</title>
</head>
<body>
<?php
require __DIR__ . '/navigation.php';
$pdfMode = !empty($pdfMode);
$esc = static fn($v) => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$rows = $reportRows ?? [];
$workerName = $workerName ?? '';
$chemicalLabel = $chemicalLabel ?? '';
$printParams = $printParams ?? array_filter([
    'declaration_id' => ($declarationId ?? ($_GET['declaration_id'] ?? null)),
    'employee_id' => ($selectedEmployee->employee_id ?? ($_GET['employee_id'] ?? null)),
    'company_id' => ($selectedCompany->company_id ?? ($_GET['company_id'] ?? null)),
    'surveillance_id' => ($surveillanceId ?? ($_GET['surveillance_id'] ?? null)),
], static fn ($value) => !empty($value));
$resolvedUser = class_exists('\\Illuminate\\Support\\Facades\\Auth') ? \Illuminate\Support\Facades\Auth::user() : null;
$footerFirst = trim((string) (($resolvedUser->first_name ?? $resolvedUser->firstName ?? '') ?: ''));
$footerLast = trim((string) (($resolvedUser->last_name ?? $resolvedUser->lastName ?? '') ?: ''));
$footerName = trim($footerFirst . ' ' . $footerLast);
if ($footerName === '') {
    $footerName = trim((string) (($resolvedUser->name ?? $username ?? 'User') ?: 'User'));
}
$generatedFooter = 'Generated by ' . $footerName . ' at ' . date('D, d M Y h:i A');
medis_render_navigation_start([
    'clinicName' => $clinicName ?? 'Medis SHAMS',
    'clinicLogoUrl' => $clinicLogoUrl ?? null,
    'username' => $username ?? 'User',
    'active' => 'report',
    'pdfMode' => $pdfMode,
]);
?>
<style>
.report-page{width:100%;max-width:none;margin:0;background:#fff;color:#0f172a;font-family:"Poppins","Segoe UI",Tahoma,Geneva,Verdana,sans-serif}
.sheet{padding:18px 18px 22px;border:1px solid #e5e7eb;border-radius:20px;background:#fff;box-shadow:0 10px 30px rgba(15,23,42,.04);width:100%}
.sheet-top{position:relative;display:block;margin-bottom:8px;text-align:center}
.sheet-top .center-title{display:block;width:100%;text-align:center;font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}
.sheet-top .right-code{position:absolute;right:0;top:0;display:block;text-align:right;font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}
.sheet-title{text-align:center;margin-bottom:12px}
.sheet-title .line{font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}
.sheet-title .main{font-size:16px;font-weight:700;line-height:1.5;margin-top:8px;color:#0f172a}
.meta{display:grid;gap:8px;margin:14px 0 16px;font-size:14px}
.meta-row{display:flex;align-items:flex-end;gap:8px}
.meta-label{min-width:160px;font-weight:600;color:#0f172a}
.meta-line{flex:1;min-height:18px;padding:0;color:#334155}
.summary-table{width:100%;border-collapse:collapse;table-layout:fixed}
.summary-table th,.summary-table td{border:1px solid #cbd5e1;padding:8px 6px;vertical-align:top;font-size:13px;line-height:1.4}
.summary-table th{background:#e8f3ec;font-weight:700;text-align:center;color:#14321f}
.summary-table td{height:224px;background:#fff;color:#334155}
.summary-table .col-no{width:4%}
.summary-table .col-date{width:9%}
.summary-table .col-type{width:14%}
.summary-table .col-history{width:11%}
.summary-table .col-clinical{width:9%}
.summary-table .col-target{width:10%}
.summary-table .col-bei{width:9%}
.summary-table .col-work{width:9%}
.summary-table .col-conclusion{width:10%}
.summary-table .col-mrp{width:9%}
.summary-table .col-doctor{width:13%}
.cell-lines{display:grid;gap:10px}
.cell-line{min-height:18px;border-bottom:1px solid transparent}
.toolbar-hide .app-card{padding:0;border:0;background:transparent;box-shadow:none}
.toolbar-hide .app-page{padding:18px;background:#f3f6f8}
.report-actions{display:flex;justify-content:flex-end;gap:10px;margin-bottom:12px}
.report-btn{display:inline-flex;align-items:center;gap:8px;text-decoration:none;border:1px solid #d1d5db;border-radius:10px;padding:8px 12px;background:#fff;color:#374151;font-size:14px;cursor:pointer}
.report-btn.primary{background:#389B5B;border-color:#389B5B;color:#fff}
.pdf-footer{margin-top:14px;padding-top:8px;border-top:1px solid #e5e7eb;text-align:right;font-size:11px;color:#64748b}
.pdf-mode .sheet{padding:0;border:0;border-radius:0;box-shadow:none}
.pdf-mode .app-page{padding:0!important;background:#fff}
.pdf-mode .report-page{padding:0}
.pdf-mode .report-actions{display:none!important}
.pdf-mode .pdf-footer{position:fixed;left:0;right:0;bottom:0;margin:0;padding-top:6px;background:#fff;border-top:1px solid #e5e7eb}
@media print{body{background:#fff}.app-topbar,.app-sidebar,.report-actions{display:none!important}.app-shell{display:block}.app-main,.app-page,.app-card{display:block;height:auto;overflow:visible;padding:0!important;border:0!important;background:#fff!important}.report-page{max-width:none}.sheet{padding:0}}
@media(max-width:900px){.summary-table{min-width:900px}.report-page{overflow:auto;width:100%}}
</style>
<div class="report-page toolbar-hide<?php echo $pdfMode ? ' pdf-mode' : ''; ?>">
    <div class="sheet">
        <?php if (!$pdfMode): ?>
        <div class="report-actions">
            <a class="report-btn" href="general_report.php">Back</a>
            <button class="report-btn primary" type="button" onclick="window.open('<?php echo $esc(route('pdf.usechh2', $printParams)); ?>', '_blank')">Print</button>
        </div>
        <?php endif; ?>

        <div class="sheet-top">
            <span class="center-title">Occupational Safety and Health Act 1994 (Act 514)</span>
            <span class="right-code">USECHH 2</span>
        </div>

        <div class="sheet-title">
            <div class="line">Use and Standard of Exposure of Chemical Hazardous to Health Regulations 2000</div>
            <div class="main">SUMMARY REPORTS OF EMPLOYEE</div>
        </div>

        <div class="meta">
            <div class="meta-row">
                <span class="meta-label">Name of Employee: </span>
                <span class="meta-line"><?php echo $esc($workerName); ?></span>
            </div>
            <div class="meta-row">
                <span class="meta-label">Name of Chemical: </span>
                <span class="meta-line"><?php echo $esc($chemicalLabel); ?></span>
            </div>
        </div>

        <table class="summary-table">
            <thead>
                <tr>
                    <th class="col-no">No.</th>
                    <th class="col-date">MS Date</th>
                    <th class="col-type">Type of Assessment</th>
                    <th class="col-history">History of Health Effects due to CHTH Exposure</th>
                    <th class="col-clinical">Clinical Findings</th>
                    <th class="col-target">Target Organ Function Test (Specify Organ)</th>
                    <th class="col-bei">BEI Determinant</th>
                    <th class="col-work">Work Relatedness</th>
                    <th class="col-conclusion">Conclusion of MS Finding (Fit/Not Fit)</th>
                    <th class="col-mrp">Date Of MRP</th>
                    <th class="col-doctor">Name of OHD/DOSH Reg. No.</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <div class="cell-lines">
                            <?php for ($i = 1; $i <= max(count($rows), 1); $i++): ?>
                                <div class="cell-line"><?php echo $i <= count($rows) ? $esc($i) : ''; ?></div>
                            <?php endfor; ?>
                        </div>
                    </td>
                    <td>
                        <div class="cell-lines">
                            <?php if (!empty($rows)): foreach ($rows as $row): ?>
                                <div class="cell-line"><?php echo $esc(!empty($row['ms_date']) && $row['ms_date'] !== '-' ? date('d/m/Y', strtotime($row['ms_date'])) : ''); ?></div>
                            <?php endforeach; else: ?>
                                <div class="cell-line"></div>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        <div class="cell-lines">
                            <?php if (!empty($rows)): foreach ($rows as $row): ?>
                                <div class="cell-line"><?php echo $esc($row['type_of_assessment'] ?? ''); ?></div>
                            <?php endforeach; else: ?>
                                <div class="cell-line"></div>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        <div class="cell-lines">
                            <?php if (!empty($rows)): foreach ($rows as $row): ?>
                                <div class="cell-line"><?php echo $esc($row['history_health_effects'] ?? ''); ?></div>
                            <?php endforeach; else: ?>
                                <div class="cell-line"></div>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        <div class="cell-lines">
                            <?php if (!empty($rows)): foreach ($rows as $row): ?>
                                <div class="cell-line"><?php echo $esc($row['clinical_findings'] ?? ''); ?></div>
                            <?php endforeach; else: ?>
                                <div class="cell-line"></div>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        <div class="cell-lines">
                            <?php if (!empty($rows)): foreach ($rows as $row): ?>
                                <div class="cell-line"><?php echo $esc($row['target_organ'] ?? ''); ?></div>
                            <?php endforeach; else: ?>
                                <div class="cell-line"></div>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        <div class="cell-lines">
                            <?php if (!empty($rows)): foreach ($rows as $row): ?>
                                <div class="cell-line"><?php echo $esc($row['bei_determinant'] ?? ''); ?></div>
                            <?php endforeach; else: ?>
                                <div class="cell-line"></div>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        <div class="cell-lines">
                            <?php if (!empty($rows)): foreach ($rows as $row): ?>
                                <div class="cell-line"><?php echo $esc($row['work_relatedness'] ?? ''); ?></div>
                            <?php endforeach; else: ?>
                                <div class="cell-line"></div>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        <div class="cell-lines">
                            <?php if (!empty($rows)): foreach ($rows as $row): ?>
                                <div class="cell-line"><?php echo $esc($row['conclusion'] ?? ''); ?></div>
                            <?php endforeach; else: ?>
                                <div class="cell-line"></div>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        <div class="cell-lines">
                            <?php if (!empty($rows)): foreach ($rows as $row): ?>
                                <div class="cell-line"><?php echo $esc(!empty($row['mrp_date']) && $row['mrp_date'] !== '-' ? date('d/m/Y', strtotime($row['mrp_date'])) : ''); ?></div>
                            <?php endforeach; else: ?>
                                <div class="cell-line"></div>
                            <?php endif; ?>
                        </div>
                    </td>
                    <td>
                        <div class="cell-lines">
                            <?php if (!empty($rows)): foreach ($rows as $row): ?>
                                <div class="cell-line"><?php echo $esc($row['doctor'] ?? ''); ?></div>
                            <?php endforeach; else: ?>
                                <div class="cell-line"></div>
                            <?php endif; ?>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>

        <div class="pdf-footer"><?php echo $esc($generatedFooter); ?></div>
    </div>
</div>
<?php medis_render_navigation_end(); ?>
</body>
</html>




