<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Surveillance Fitness Report</title>
</head>
<body>
<?php
require __DIR__ . '/navigation.php';
$pdfMode = !empty($pdfMode);
$esc = static fn($v) => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$backUrl = function_exists('route') ? route('general.report') : 'general_report.php';
$saveUrl = function_exists('route') ? route('surveillance.report.fitness.save') : '#';
$employee = $selectedEmployee ?? null;
$company = $selectedCompany ?? null;
$chemical = $chemicalInfo ?? null;
$fitness = $fitnessRespirator ?? null;
$ms = $msFindings ?? null;
$doctorProfile = $doctor ?? null;
$certificates = $certificates ?? [[
    'person_name' => trim((string) ((($employee->employee_firstName ?? '') . ' ' . ($employee->employee_lastName ?? '')))),
    'identity_no' => $employee->employee_NRIC ?? ($employee->employee_passportNo ?? ''),
    'dob' => $employee->employee_DOB ?? '',
    'sex' => $employee->employee_gender ?? '',
    'employer' => $company->company_name ?? '',
    'employee_address' => $company->company_address ?? '',
    'exam_date' => $chemical->examination_date ?? '',
    'tests_done' => $chemical->chemicals ?? '',
    'fitness_result' => $ms->conclusion_fitness ?? ($fitness->fitness_result ?? ''),
    'remarks' => $fitness->fitness_justification ?? '',
    'doctor_name' => trim((string) ((($doctorProfile->doctor_firstName ?? '') . ' ' . ($doctorProfile->doctor_lastName ?? '')))),
    'doctor_reg_no' => $doctorProfile->doctor_registrationNo ?? '',
    'practice_address' => $doctorProfile->doctor_practiceAddress ?? '',
]];
$resolvedUser = class_exists('\\Illuminate\\Support\\Facades\\Auth') ? \Illuminate\Support\Facades\Auth::user() : null;
$footerFirst = trim((string) (($resolvedUser->first_name ?? $resolvedUser->firstName ?? '') ?: ''));
$footerLast = trim((string) (($resolvedUser->last_name ?? $resolvedUser->lastName ?? '') ?: ''));
$footerName = trim($footerFirst . ' ' . $footerLast);
if ($footerName === '') {
    $footerName = trim((string) (($resolvedUser->name ?? $username ?? 'User') ?: 'User'));
}
$generatedFooter = 'Generated by ' . $footerName . ' at ' . date('D, d M Y h:i A');
medis_render_navigation_start([
    'clinicName' => $clinicName ?? 'Medis SHAMS',
    'clinicLogoUrl' => $clinicLogoUrl ?? null,
    'username' => $username ?? 'User',
    'active' => '',
    'pdfMode' => $pdfMode,
]);
?>
<style>
.report-page{width:100%;max-width:none;margin:0;color:#0f172a;font-family:"Poppins","Segoe UI",Tahoma,Geneva,Verdana,sans-serif;background:#fff}
.sheet-stack{display:grid;gap:18px}
.sheet{padding:28px 30px;border:1px solid #e5e7eb;border-radius:20px;background:#fff;box-shadow:0 10px 30px rgba(15,23,42,.04)}
.report-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:16px}
.report-btn{display:inline-flex;align-items:center;gap:8px;text-decoration:none;border:1px solid #d1d5db;border-radius:10px;padding:8px 14px;background:#fff;color:#374151;font-size:14px;font-weight:500;cursor:pointer}
.report-btn.primary{background:#389B5B;border-color:#389B5B;color:#fff}
.sheet-top{position:relative;display:block;margin-bottom:8px;text-align:center}
.center-title{display:block;width:100%;text-align:center;font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}
.right-code{position:absolute;right:0;top:0;display:block;text-align:right;font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}
.sheet-title{text-align:center;margin-bottom:20px}
.sheet-title .line{font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}
.sheet-title .main{font-size:16px;font-weight:700;line-height:1.5;margin-top:8px;color:#0f172a}
.section-rule{display:none}
.certificate-body{display:grid;gap:18px;font-size:13px;line-height:1.6;color:#0f172a}.spacer-after-employee{margin-bottom:14px}.spacer-before-remarks{margin-bottom:16px}
.inline-row{display:flex;flex-wrap:wrap;gap:0;font-size:13px;line-height:1.6}
.inline-row strong{font-weight:700}
.inline-text{display:inline}
.remarks-block{display:grid;gap:8px}
.remarks-label{font-size:13px;font-weight:700;color:#0f172a}
.remarks-box{width:100%;min-height:86px;padding:10px 12px;color:#334155;font-size:13px;line-height:1.7;border:1px solid #cbd5e1;border-radius:12px;background:#fff;resize:vertical;font:inherit}
.signature-area{margin-top:22px;padding-top:6px;display:grid;justify-content:end;gap:14px}
.signature-top{display:grid;justify-content:end;text-align:right;gap:8px;width:min(420px,100%)}
.signature-image{display:flex;justify-content:flex-end;min-height:52px}
.signature-image img{max-height:56px;max-width:180px;object-fit:contain}
.signature-date{font-size:13px;color:#0f172a}
.signature-meta{display:grid;gap:10px;font-size:13px;line-height:1.5;color:#0f172a;width:min(420px,100%)}
.signature-meta div{text-align:right}
.signature-meta strong{font-weight:700}
.pdf-footer{margin-top:14px;padding-top:8px;border-top:1px solid #e5e7eb;text-align:right;font-size:11px;color:#64748b}
.toolbar-hide .app-card{padding:0;border:0;background:transparent;box-shadow:none}
.toolbar-hide .app-page{padding:18px;background:#f3f6f8}
.pdf-mode .sheet{padding:0;border:0;border-radius:0;box-shadow:none}
.pdf-mode .app-page{padding:0!important;background:#fff}
.pdf-mode .report-page{padding:0;background:#fff}
.pdf-mode .report-actions{display:none!important}
.pdf-mode .pdf-footer{position:fixed;left:0;right:0;bottom:0;margin:0;padding-top:6px;background:#fff;border-top:1px solid #e5e7eb}
@media(max-width:760px){.sheet{padding:18px 18px 22px}.signature-area{justify-content:stretch}.signature-top{justify-content:stretch;text-align:left;width:100%}.signature-image{justify-content:flex-start}.signature-meta{width:100%}.signature-meta div{text-align:left}}
@media print{body{background:#fff}.app-topbar,.app-sidebar,.report-actions{display:none!important}.app-shell{display:block}.app-main,.app-page,.app-card{display:block;height:auto;overflow:visible;padding:0!important;border:0!important;background:#fff!important}.sheet{padding:0;border:0;border-radius:0;box-shadow:none}.report-page{background:#fff}}
</style>
<div class="report-page toolbar-hide<?php echo $pdfMode ? ' pdf-mode' : ''; ?>">
    <form method="POST" action="<?php echo $esc($saveUrl); ?>">
        <input type="hidden" name="_token" value="<?php echo $esc(csrf_token()); ?>">
        <input type="hidden" name="employee_id" value="<?php echo $esc($employee->employee_id ?? ''); ?>">
        <input type="hidden" name="company_id" value="<?php echo $esc($company->company_id ?? ''); ?>">
        <input type="hidden" name="surveillance_id" value="<?php echo $esc($surveillanceId ?? ''); ?>">
        <div class="sheet-stack">
            <?php foreach ($certificates as $certificate): ?>
                <section class="sheet">
                    <div class="sheet-top">
                        <span class="center-title">Occupational Safety and Health Act 1994 (Act 514)</span>
                        <span class="right-code">USECHH 3</span>
                    </div>

                    <div class="sheet-title">
                        <div class="line">Use and Standard of Exposure of Chemicals Hazardous to Health Regulations 2000</div>
                        <div class="main">CERTIFICATE OF FITNESS</div>
                    </div>
<div class="certificate-body">
                        <div class="inline-row">
                            <span class="inline-text"><strong>Name of Person examined:</strong> <?php echo $esc($certificate['person_name'] ?? ''); ?></span>
                            <span class="inline-text"> <strong>NRIC/ Passport No.:</strong> <?php echo $esc($certificate['identity_no'] ?? ''); ?></span>
                        </div>

                        <div class="inline-row">
                            <span class="inline-text"><strong>Date of Birth: </strong> <?php echo $esc(!empty($certificate['dob']) ? date('d/m/Y', strtotime($certificate['dob'])) : ''); ?></span>
                            <span class="inline-text"> <strong>Sex: </strong> <?php echo $esc($certificate['sex'] ?? ''); ?></span>
                        </div>

                        <div class="inline-row">
                            <span class="inline-text"><strong>Name &amp; Address of Employee:</strong> <?php echo $esc(trim(($certificate['employer'] ?? '') . (!empty($certificate['employee_address']) ? ', ' . $certificate['employee_address'] : ''))); ?></span>
                        </div>

                        <div class="inline-row">
                            <span class="inline-text">I hereby certify that I have examined the above-named person on <strong><?php echo $esc(!empty($certificate['exam_date']) ? date('d/m/Y', strtotime($certificate['exam_date'])) : ''); ?></strong> and he/she is <strong><?php echo $esc($certificate['fitness_result'] ?? ''); ?></strong> for work which may expose him/her to <strong><?php echo $esc($certificate['tests_done'] ?? ''); ?></strong>.</span>
                        </div>

                        <div class="remarks-block">
                            <div class="remarks-label">Remarks (if any):  <?php if ($pdfMode): ?><span style="font-weight:500; color:#0f172a;"><?php $remarksValue = trim((string) ($certificate['remarks'] ?? '')); echo $esc($remarksValue !== '' ? $remarksValue : 'N/A'); ?></span><?php endif; ?></div>
                            <?php if (!$pdfMode): ?>
                                <textarea class="remarks-box" name="remarks" placeholder="Insert remarks"><?php echo $esc(old('remarks', $certificate['remarks'] ?? '')); ?></textarea>
                            <?php endif; ?>
                            <input type="hidden" name="fitness_result" value="<?php echo $esc($certificate['fitness_result'] ?? ''); ?>">
                            <input type="hidden" name="exam_date" value="<?php echo $esc($certificate['exam_date'] ?? ''); ?>">
                            <input type="hidden" name="tests_done" value="<?php echo $esc($certificate['tests_done'] ?? ''); ?>">
                        </div>
                    </div>

                    <div class="signature-area">
                        <div class="signature-top">
                            <div><strong>Signature &amp; Date:</strong></div>
                            <?php $signaturePath = trim((string) ($doctorProfile->doctor_sign ?? $doctorProfile->signature_path ?? '')); ?>
                            <?php if ($signaturePath !== '' && !$pdfMode): ?>
                                <div class="signature-image"><img src="<?php echo $esc($signaturePath); ?>" alt="Doctor signature"></div>
                            <?php elseif ($signaturePath !== ''): ?>
                                <div class="signature-image"><img src="<?php echo $esc($signaturePath); ?>" alt="Doctor signature"></div>
                            <?php endif; ?>
                            <div class="signature-date"><?php echo $esc(!empty($certificate['exam_date']) ? date('d/m/Y', strtotime($certificate['exam_date'])) : ''); ?></div>
                        </div>

                        <div class="signature-meta">
                            <div><strong>Name of occupational Health Doctor: </strong> <?php echo $esc($certificate['doctor_name'] ?? ''); ?></div>
                            <div><strong>DOSH Reg. No.:</strong> <?php echo $esc($certificate['doctor_reg_no'] ?? ''); ?></div>
                            <div><strong>Address of Practice: </strong> <?php echo $esc($certificate['practice_address'] ?? ''); ?></div>
                        </div>
                    </div>

                    <div class="pdf-footer"><?php echo $esc($generatedFooter); ?></div>
                </section>
            <?php endforeach; ?>
        </div>
        <?php if (!$pdfMode): ?>
        <div class="report-actions">
            <a class="report-btn" href="<?php echo $esc($backUrl); ?>">Back</a>
            <button class="report-btn primary" type="submit">Save</button>
        </div>
        <?php endif; ?>
    </form>
</div>
<?php medis_render_navigation_end(); ?>
</body>
</html>







