<?php
require __DIR__ . '/navigation.php';

$pdfMode = !empty($pdfMode);
$esc = static fn($v) => htmlspecialchars((string) $v, ENT_QUOTES, 'UTF-8');
$backUrl = function_exists('route') ? route('general.report') : 'general_report.php';
$saveUrl = function_exists('route') ? route('surveillance.report.removal.save') : '#';
$employee = $selectedEmployee ?? null;
$company = $selectedCompany ?? null;
$chemical = $chemicalInfo ?? null;
$doctorProfile = $doctor ?? null;
$ms = $msFindings ?? null;
$fitness = $fitnessReportRow ?? null;
$existingRemoval = $existingRemoval ?? null;

$printParams = array_filter([
    'declaration_id' => $declarationId ?? ($declaration->declaration_id ?? null),
    'employee_id' => $employee->employee_id ?? null,
    'company_id' => $company->company_id ?? null,
    'surveillance_id' => $surveillanceId ?? null,
], static fn($value) => $value !== null && $value !== '');
$printUrl = function_exists('route') ? route('pdf.usechh5i', $printParams) : 'PDF_USECHH5i.php';

$resolvedUser = class_exists('\Illuminate\Support\Facades\Auth') ? \Illuminate\Support\Facades\Auth::user() : null;
$footerFirst = trim((string) (($resolvedUser->first_name ?? $resolvedUser->firstName ?? '') ?: ''));
$footerLast = trim((string) (($resolvedUser->last_name ?? $resolvedUser->lastName ?? '') ?: ''));
$footerName = trim($footerFirst . ' ' . $footerLast);
if ($footerName === '') {
    $footerName = trim((string) (($resolvedUser->name ?? $username ?? 'User') ?: 'User'));
}
$generatedFooter = 'Generated by ' . $footerName . ' at ' . date('D, d M Y h:i A');

$fmtDate = static function ($value, string $fallback = 'N/A'): string {
    $value = trim((string) ($value ?? ''));
    if ($value === '') {
        return $fallback;
    }
    $time = strtotime($value);
    return $time ? date('d/m/Y', $time) : $value;
};

$workerName = trim((string) (($employee->employee_firstName ?? '') . ' ' . ($employee->employee_lastName ?? '')));
$doctorName = trim((string) (($doctorProfile->doctor_firstName ?? '') . ' ' . ($doctorProfile->doctor_lastName ?? '')));
$identityNo = trim((string) (($employee->employee_NRIC ?? '') !== '' ? ($employee->employee_NRIC ?? '') : ($employee->employee_passportNo ?? '')));
$workplaceName = trim((string) ($company->company_name ?? ''));
$workplaceAddress = trim((string) ($company->company_address ?? ''));
$contactEmail = trim((string) ($doctorProfile->doctor_email ?? ''));
$hpNumber = trim((string) (($doctorProfile->doctor_hp ?? $doctorProfile->doctor_hpNo ?? '')));
$telNumber = trim((string) (($doctorProfile->doctor_tel ?? $doctorProfile->doctor_telephone ?? '')));
$faxNumber = trim((string) ($doctorProfile->doctor_fax ?? ''));
$removalType = trim((string) ($existingRemoval->removal_type ?? ''));
$reasonText = trim((string) ($existingRemoval->reasons_recommendations ?? ''));
$reasonParts = array_values(array_filter(array_map('trim', explode(';', $reasonText)), static fn($value) => $value !== ''));
$doctorReg = trim((string) (($doctorProfile->doctor_registrationNo ?? $doctorProfile->OHD_registrationNo ?? '')));
$practiceAddress = trim((string) ($doctorProfile->doctor_practiceAddress ?? ''));
$jobLabel = trim((string) ($fitness->result ?? ($ms->conclusion_fitness ?? '')));
$examDate = $chemical->examination_date ?? null;
$employmentStart = $employee->employee_DOE ?? null;
$yearsService = trim((string) ($employee->years_of_service ?? ''));
$hazardPresent = trim((string) ($chemical->chemicals ?? ''));

$hasReason = static function (string $needle) use ($reasonParts): bool {
    foreach ($reasonParts as $part) {
        if (stripos($part, $needle) !== false) {
            return true;
        }
    }
    return false;
};
$otherReason = 'N/A';
foreach ($reasonParts as $part) {
    if (stripos($part, 'Other:') === 0) {
        $otherReason = trim(substr($part, 6));
        break;
    }
}

medis_render_navigation_start([
    'clinicName' => $clinicName ?? 'Medis SHAMS',
    'clinicLogoUrl' => $clinicLogoUrl ?? null,
    'username' => $username ?? 'User',
    'active' => '',
    'pdfMode' => $pdfMode,
]);
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Surveillance Removal Report</title>
</head>
<body>
<style>
.report-page{width:100%;max-width:none;margin:0;color:#0f172a;font-family:"Poppins","Segoe UI",Tahoma,Geneva,Verdana,sans-serif;background:#fff}.sheet{padding:24px 26px;border:1px solid #e5e7eb;border-radius:20px;background:#fff;box-shadow:0 10px 30px rgba(15,23,42,.04)}.report-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:16px}.report-btn{display:inline-flex;align-items:center;gap:8px;text-decoration:none;border:1px solid #d1d5db;border-radius:10px;padding:8px 14px;background:#fff;color:#374151;font-size:14px;font-weight:500;cursor:pointer}.report-btn.primary{background:#389B5B;border-color:#389B5B;color:#fff}.sheet-top{position:relative;display:block;text-align:center;margin-bottom:10px}.center-title{display:block;width:100%;text-align:center;font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}.right-code{position:absolute;right:0;top:0;font-size:13px;font-weight:700;line-height:1.55;color:#0f172a}.sheet-title{text-align:center;margin-bottom:16px}.sheet-title .line{font-size:13px;font-weight:700;line-height:1.5;color:#0f172a}.sheet-title .main{font-size:16px;font-weight:700;line-height:1.5;margin-top:10px;color:#0f172a}.removal-type-line{text-align:center;font-size:14px;color:#334155;margin:14px 0 18px}.removal-type-line strong{color:#0f172a}.line-list{display:grid;gap:10px}.line-row{display:flex;align-items:flex-start;gap:8px;flex-wrap:wrap}.line-label{min-width:230px;font-size:14px;font-weight:500;color:#0f172a}.line-value{flex:1;color:#334155;line-height:1.7}.paragraphs{display:grid;gap:12px;margin-top:16px}.paragraph-line{font-size:14px;line-height:1.8;color:#0f172a}.reason-section{display:grid;gap:12px;margin-top:18px}.reason-title{font-size:14px;color:#0f172a}.reason-summary{font-size:14px;line-height:1.8;color:#334155}.reason-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px 28px}.reason-item{display:flex;align-items:flex-start;gap:10px;font-size:14px;color:#334155}.reason-box{width:20px;height:20px;border:1px solid #cbd5e1;border-radius:4px;display:inline-flex;align-items:center;justify-content:center;color:#389B5B;font-weight:700;flex-shrink:0;margin-top:1px}.doctor-block{display:grid;gap:12px;margin-top:18px}.doctor-row{display:grid;grid-template-columns:210px 1fr;gap:14px;align-items:start}.doctor-label{font-size:14px;font-weight:600;color:#0f172a}.doctor-value{color:#334155;line-height:1.7}.contact-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px;margin-top:8px}.contact-card{display:grid;gap:6px}.contact-card label{font-size:13px;font-weight:600;color:#334155}.contact-value{min-height:24px;color:#334155}.sign-grid{display:grid;grid-template-columns:minmax(0,1fr) 180px;gap:48px;margin-top:30px;align-items:end}.sign-box{display:grid;gap:8px}.sign-rule{height:34px;border-bottom:1px solid #94a3b8}.sign-text{text-align:center;font-size:13px;color:#334155}.date-value{text-align:center;font-size:13px;color:#334155}.notice{margin-top:18px;padding-top:12px;border-top:1px solid #e5e7eb;font-size:12.5px;line-height:1.55;color:#475569}.pdf-footer{margin-top:18px;padding-top:8px;border-top:1px solid #e5e7eb;text-align:right;font-size:11px;color:#64748b}.toolbar-hide .app-card{padding:0;border:0;background:transparent;box-shadow:none}.toolbar-hide .app-page{padding:18px;background:#f3f6f8}.pdf-mode .sheet{padding:0;border:0;border-radius:0;box-shadow:none}.pdf-mode .app-page{padding:0!important;background:#fff}.pdf-mode .report-page{padding:0;background:#fff}.pdf-mode .report-actions{display:none!important}.pdf-mode .pdf-footer{position:fixed;left:0;right:0;bottom:0;margin:0;padding-top:6px;background:#fff;border-top:1px solid #e5e7eb}.error-box{margin-bottom:14px;padding:12px 14px;border:1px solid #fecaca;background:#fef2f2;color:#b91c1c;border-radius:12px}@media(max-width:900px){.sheet{padding:18px}.toggle-row,.reason-grid,.contact-grid,.sign-grid{grid-template-columns:1fr}.report-page{overflow:auto;width:100%}.line-row,.doctor-row{align-items:flex-start}.line-label,.doctor-label{min-width:180px;padding-top:8px}.sign-grid{gap:18px}}@media print{body{background:#fff}.app-topbar,.app-sidebar,.report-actions{display:none!important}.app-shell{display:block}.app-main,.app-page,.app-card{display:block;height:auto;overflow:visible;padding:0!important;border:0!important;background:#fff!important}.sheet{padding:0;box-shadow:none;border:0}}
</style>
<div class="report-page toolbar-hide<?php echo $pdfMode ? ' pdf-mode' : ''; ?>">
    <?php if (!$pdfMode && isset($errors) && $errors->any()): ?>
        <div class="error-box"><?php echo $esc($errors->first()); ?></div>
    <?php endif; ?>
    <form method="POST" action="<?php echo $esc($saveUrl); ?>">
        <input type="hidden" name="_token" value="<?php echo $esc(csrf_token()); ?>">
        <input type="hidden" name="employee_id" value="<?php echo $esc($employee->employee_id ?? ''); ?>">
        <input type="hidden" name="company_id" value="<?php echo $esc($company->company_id ?? ''); ?>">
        <input type="hidden" name="surveillance_id" value="<?php echo $esc($surveillanceId ?? ''); ?>">
        <div class="sheet">
            <div class="sheet-top">
                <span class="center-title">Occupational Safety and Health Act 1994 (Act 514)</span>
                <span class="right-code">USECHH 5i</span>
            </div>
            <div class="sheet-title">
                <div class="line">Use and Standard of Exposure of Chemicals Hazardous to Health Regulation</div>
                <div class="main">MEDICAL REMOVAL PROTECTION</div>
            </div>
            <div class="removal-type-line"><strong>Type of Removal: </strong> <?php echo $esc($removalType !== '' ? $removalType : 'N/A'); ?></div>
            <div class="line-list">
                <div class="line-row"><span class="line-label">1. Name of Worker: </span><span class="line-value"><?php echo $esc($workerName !== '' ? $workerName : 'N/A'); ?></span></div>
                <div class="line-row"><span class="line-label">2. NRIC/Passport No: </span><span class="line-value"><?php echo $esc($identityNo !== '' ? $identityNo : 'N/A'); ?></span></div>
                <div class="line-row"><span class="line-label">3. Date of Birth: </span><span class="line-value"><?php echo $esc($fmtDate($employee->employee_DOB ?? null)); ?></span></div>
                <div class="line-row"><span class="line-label">4. Sex: </span><span class="line-value"><?php echo $esc(trim((string) ($employee->employee_gender ?? '')) !== '' ? (string) $employee->employee_gender : 'N/A'); ?></span></div>
                <div class="line-row"><span class="line-label">5. Name and Address of Workplace:  </span><span class="line-value"><?php echo $esc(trim($workplaceName . ($workplaceAddress !== '' ? ', ' . $workplaceAddress : '')) ?: 'N/A'); ?></span></div>
                <div class="line-row"><span class="line-label">6. Date of starting employment: </span><span class="line-value"><?php echo $esc($fmtDate($employmentStart)); ?></span><span class="line-label" style="min-width:210px;">Duration of Employment (Years): </span><span class="line-value" style="flex:0 0 120px;"><?php echo $esc($yearsService !== '' ? $yearsService : 'N/A'); ?></span></div>
                <div class="line-row"><span class="line-label">7. Health Hazard Present: </span><span class="line-value"><?php echo $esc($hazardPresent !== '' ? $hazardPresent : 'N/A'); ?></span></div>
            </div>
            <div class="paragraphs">
                <div class="paragraph-line">I certify that the above named person examined by me on <strong><?php echo $esc($fmtDate($examDate)); ?></strong> should not continue to work as <strong><?php echo $esc($jobLabel !== '' ? $jobLabel : 'N/A'); ?></strong> in <strong><?php echo $esc($workplaceName !== '' ? $workplaceName : 'N/A'); ?></strong>.</div>
            </div>
            <div class="reason-section">
                <div class="reason-summary"><strong>The reasons for my recommendations are as follows:</strong> <?php echo $esc($reasonText !== '' ? $reasonText : 'N/A'); ?></div>
            </div>
            <div class="doctor-block">
                <div class="doctor-row"><span class="doctor-label">Name of OHD: </span><span class="doctor-value"><?php echo $esc($doctorName !== '' ? $doctorName : 'N/A'); ?></span></div>
                <div class="doctor-row"><span class="doctor-label">OHD Registration No: </span><span class="doctor-value"><?php echo $esc($doctorReg !== '' ? $doctorReg : 'N/A'); ?></span></div>
                <div class="doctor-row"><span class="doctor-label">Address of Practice: </span><span class="doctor-value"><?php echo $esc($practiceAddress !== '' ? $practiceAddress : 'N/A'); ?></span></div>
                <div class="doctor-row"><span class="doctor-label">Email address:  </span><span class="doctor-value"><?php echo $esc($contactEmail !== '' ? $contactEmail : 'N/A'); ?></span></div>
                <div class="doctor-row"><span class="doctor-label">Phone Number: </span><span class="doctor-value"><?php echo $esc(($hpNumber !== '' ? $hpNumber : ($telNumber !== '' ? $telNumber : 'N/A'))); ?></span></div>
                <div class="doctor-row"><span class="doctor-label">Fax: </span><span class="doctor-value"><?php echo $esc($faxNumber !== '' ? $faxNumber : 'N/A'); ?></span></div>
                <div class="doctor-row"><span class="doctor-label">OHD Signature &amp; Date:</span><span class="doctor-value"><?php echo $esc($fmtDate($examDate)); ?></span></div>
            </div>
            <div class="notice">Note: This certificate should be completed in triplicate and the original copy forwarded to the director General, Department of Occupational Safety and Health. Putrajaya and must include the actual results of the relevant examination/tests. The quantitative results (e.g. blood lead) the exact diagrams and measurements units must be clearly stated. Also include a copy of qualitative results (e.g Chest X-ray). Incomplete form will not be accepted.</div>
            <div class="pdf-footer"><?php echo $esc($generatedFooter); ?></div>
        </div>
        <?php if (!$pdfMode): ?>
        <div class="report-actions">
            <a class="report-btn" href="<?php echo $esc($backUrl); ?>">Back</a>
            <button class="report-btn primary" type="submit">Save</button>
            <a class="report-btn" href="<?php echo $esc($printUrl); ?>" target="_blank" rel="noopener">Print</a>
        </div>
        <?php endif; ?>
    </form>
</div>
<?php medis_render_navigation_end(); ?>
</body>
</html>











